---
# This playbook is meant to be an easy introduction to using Ansible Tower to 
# deploy VMs to Azure

# the job template should be run on localhost (or whatever worker node with prereqs)
# node must have pysphere installed: pip install msrestazure

- name: Deploy Azure VM
  hosts: all
  connection: local
  # use cloud credentials in Tower for Azure access
  # define a survey for any parameters that you want to prompt users for 
  tasks:
    - name: Create VM
      azure_rm_virtualmachine:
        # the lookups here are taking infromation from the tower cloud credentials
        # define azure cloud credentials in Tower and ensure they are referenced
        # in the job template 
        subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
        management_cert_path: "{{ lookup('env', 'AZURE_CERT_PATH') }}"
        resource_group: myResourceGroup
        vm_size: Standard_DS1_v2
        name: "{{ vm_name }}"
        admin_username: az_user
        image:
          offer: RHEL
          publisher: RedHat
          sku: '7.3'
          version: latest